### ISSUE TITLE
This resource pack infringes VANILLATWEAKS' copyright.

### ISSUE THREAD

**Issue by blryface** [CosmoHigh/minecraftfixes#3]
Please just put some effort into making something unique, instead of deleting my issue and saying "fixed".

**Comment by CosmoHigh** [comment]
Who says you can't?

**Comment by CosmoHigh** [comment]
1. STOP DAMAGING MY REPUTATION
2. IT SAYS MADE WITH VANILLATWEAKS ON THE PAGE

**Comment by blryface** [comment]
I am not damaging your reputation. You're the one that doesn't know how copyright works.
As seen in the terms of Vanilla Tweaks, you can't just distribute their packs as-is. They can be part of a bigger project or used as a base for your project with proper modification. I've went trough your zip file, and it's doing neither of those.
You are infringing VanillaTweaks' copyright, and saying you're using their assets does not mean you stopped infringing it.

**Comment by andre-paulo98** [comment]
Hi there,
I'm André from the Vanilla Tweaks team.
Please delete the following file: https://github.com/CosmoHigh/minecraftfixes/blob/main/Connor's%20Fixing%20Addon%20for%20Java.zip or we'll submit a DMCA Takedown request to GitHub.

Our terms/license doesn't allow reupload of our assets as it is, you can read it here: https://vanillatweaks.net/terms/
If you want to share a pack you made, you should link the share link you can generate in our website by pressing the "Share" button.

**Comment by CosmoHigh** [comment]
![image](https://github.com/CosmoHigh/minecraftfixes/assets/113015055/faa0831f-7b81-44df-bd64-2685ab5fbb2c)
It says to credit on the page so I did.
![image](https://github.com/CosmoHigh/minecraftfixes/assets/113015055/aac84bcf-3832-43b2-ba40-4d21412b24e8)

**Comment by blryface** [comment]
I'm starting to think you cannot read

**Comment by CosmoHigh** [comment]
OH MY GOD IT'S AN OLD FREAKING PACK MATE! I AM WORKING ON UPDATING IT! AND THEN I CAN FIX IT!

**Comment by CosmoHigh** [comment]
I can read! I understand that I must modify it before sending it out! I am doing that now.
